#!/bin/bash
#
# Usage: ./minion [task:name] [--option1=optval1 --option2=optval2]
#
# And so on.
#
# To get help, pass in --help
#
# # Minion general help
# ./minion --help
# ./minion
#
# # Task specific help
# ./minion task:name --help
#

if [[ $# > 0 && $1 != --* ]]
then
	TASK="--task=$1"
	shift 1
fi

php index.php --uri=minion "$TASK" "$@"

# Echo a new line because Minion_CLI::write() prepends them now
echo -e "\n"

# Pass the exit code back out
exit $?